/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auto.module';
import * as i2 from './auto.service';
export const AutoCompleteModuleNgFactory:i0.NgModuleFactory<i1.AutoCompleteModule> = i0.ɵcmf(i1.AutoCompleteModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AutoCompleteService,i2.AutoCompleteService,([] as any[])),i0.ɵmpd(512,
          i1.AutoCompleteModule,i1.AutoCompleteModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdXNlci9Eb2N1bWVudHMvaGFyZHlQL25nNC1hdXRvLWNvbXBsZXRlL2F1dG8ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdXNlci9Eb2N1bWVudHMvaGFyZHlQL25nNC1hdXRvLWNvbXBsZXRlL2F1dG8ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
